name: genzeh911
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  auto_animated: ^3.2.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  get_storage: ^2.1.1
  provider: ^6.1.2
  firebase_messaging: ^15.1.6
  google_maps_flutter: ^2.10.0
  dio: ^5.7.0
  lottie: ^3.2.0
  google_fonts: ^6.2.1
  package_info_plus: ^8.1.1
  get_it: ^8.0.2
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  intl: ^0.20.1
  rxdart: ^0.28.0
  device_info_plus: ^11.1.1
  dotted_line: ^3.2.3
  geocoding: ^3.0.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  internet_connection_checker: ^3.0.0
  sign_in_with_apple: ^6.1.4
  fluttertoast: ^8.2.8
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.16
  # flutter_app_badger: ^1.5.0

dev_dependencies:
  dependency_validator: ^4.1.0
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
flutter_gen:
  # Optional
  output: lib/gen/
  # Optional
  line_length: 80

  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false
    
  colors:
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AppColors

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/color/
    - assets/icons/
    - assets/images/

