name: genzeh911
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  flutter_screenutil: ^5.9.3
  provider: ^6.1.2
  auto_animated: ^3.2.0
  get: ^4.6.6
  get_storage: ^2.1.1
  dio: ^5.7.0
  rxdart: ^0.28.0
  intl: ^0.19.0
  get_it: ^8.0.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  dotlottie_loader: ^0.0.4
  lottie: ^3.1.2
  flutter_svg: ^2.0.15
  flutter_gen: ^5.8.0
  pin_code_fields: ^8.0.1
  percent_indicator: ^4.2.4
  device_preview: ^1.2.0
  custom_navigation_bar: ^0.8.2
  flutter_input_chips: ^1.0.3
  intl_phone_field: ^3.2.0
  flutter_otp_text_field: ^1.2.0
  image_picker: 
  persistent_bottom_nav_bar: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/
  line_length:
    80
  

  # Optional
  integrations:
    flutter_svg: false
    flare_flutter: false
    rive: false
    lottie: false
    
  colors:
    inputs:
      - assets/color/colors.xml

    outputs:
      class_name: AppColors

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/color/
    - assets/icons/
    - assets/images/

